name: positron
channels:
  - defaults
dependencies:
  - python=3.11
  - setuptools
  - pip
  - eigen
  - loguru
  - vtk=9.*
  - pip:
      - matplotlib
      - mrcfile
      - numpy
      - scikit-learn
      - scipy
      - tensorboard
      - torch==2.2.*
      - torchvision
      - tqdm
      - starfile
      - umap-learn
      - imageio